version: '3.8'

services:
  client:
    image: visweshdocker/pmcclientside
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_URL=http://VM_IP:3000/

  server:
    image: visweshdocker/pmcserverside
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - TOKEN=jab
      - MONGOURL=MONGOURL
      - AITOKEN=CLARETOKEN
      - SERVERURL=http://VM_IP:3000
      - CLIENTURL=http://VM_IP:5173

  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - "8080:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
